GET http://localhost:8080/api/attachment-files/download/0f4ef12b-e456-4eeb-8cc9-b578a1b2acb2/type/test2
Authorization: Bearer {{accessToken}}

###

GET http://localhost:8080/api/attachment-files/download/0f4ef12b-e456-4eeb-8cc9-b578a1b2acb2/type/VueEditorImage?accessToken=test

###

POST http://localhost:8080/api/attachment-files
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test.txt"

< C:/test.txt
--boundary
Content-Disposition: form-data; name="downloadType"

test
--boundary
