GET http://localhost:8080/api/roles
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8080/api/roles?dataType=simple
Authorization: Bearer {{accessToken}}


###
GET http://localhost:8080/api/roles/ROLE_TEST
Authorization: Bearer {{accessToken}}

###
PUT http://localhost:8080/api/roles/ROLE_TEST2
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "description": "테스트",
  "userIdList": [
    "09ede404-129d-4fe1-bb40-8130b09813df",
    "1023a4a4-0688-4122-b817-3ff314f38a92",
    "1196a0fe-7aee-41ab-a98e-fa5002bf07d1",
    "4da4633a-fc69-4684-8d89-587eee0d5038",
    "99700834-b0dd-406a-b054-c39544df9b37",
    "a3c6bd16-25a9-497e-abbc-7203229a77d1",
    "da4bf167-97db-4aae-b4b7-586f73058736",
    "edc791ca-8957-44b5-8deb-ecb7e38a4dda"
  ]
}

###
PUT http://localhost:8080/api/roles/ROLE_TEST2
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "description": "테스트",
  "userIdList": []
}

###
DELETE http://localhost:8080/api/roles/ROLE_TEST2
Authorization: Bearer {{accessToken}}
